
sql_loss_impl: "v2_v2r_v3_v3r"
training_mode: "sql-onpolicy"
mix_strategy: null
# target_model_setting:
update_method: "polyak"
update_steps: null
learning_rate: 0.001
# reward_shaping:
enabled: true
old_min: 0
old_max: 100
new_min: -10
new_max: 10
# prompt_generation_setting:
top_k: null
top_p: 1.0
num_beams: 1
